### ISSUE TITLE
Setting join: all doesn't do anything.

### ISSUE THREAD

**Issue by JiK** [MaskRay/telegramircd#12]
When I set `join: all`, it doesn't autojoin to all channels on connect.

The only part of the code referring to this option is [lines 1956-1957](https://github.com/MaskRay/telegramircd/blob/76ce9f55fc9ffd5bb7e20e7e6b450771c6baca16/telegramircd.py#L1956) where a nonexistent function `Server.auto_join()` is called. This gives an error.

```
Traceback (most recent call last):
  File "telegramircd.py", line 313, in init
    await web.channel_list()
  File "telegramircd.py", line 288, in channel_list
    server.ensure_special_room(data)
  File "telegramircd.py", line 1957, in ensure_special_room
    self.auto_join(room)
AttributeError: 'Server' object has no attribute 'auto_join'
```

So:
1. These lines probably should be looping over `self.auth_clients()` and calling `client.auto_join` for each client.
2. This should be done after authentication if `options.join=='all'`. (Currently apparently the user can ensure this function is called by the IRC command `/list` but that's not what this option is supposed to do.)

**Comment by MaskRay** [comment]
Fixed `--join all` to behave like `--join auto`. The option was added when ownership of groups/users is in the client side (for the purpose of multiple different accounts), I later dropped the idea and one server handled just one account and the server can keep running in the background without any clients attached. Not clear whether `--join all` is still useful.
