### ISSUE TITLE
Channel members are missing from some rooms

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#13]
Getting a few errors in my lists, the service seems to do this at launch now.
If needed I can supply the full traceback with names redacted.

**Comment by rodneyrod** [comment]
ERROR: channel_members {'name': '[ROOM NAME HERE]', 'peer': <telethon.tl.types.PeerChannel object at 0x7ff29c76e198>}
Traceback (most recent call last):
  File "./telegramircd.py", line 303, in channel_members
    self.channel_get_participants(channel)
  File "./telegramircd.py", line 171, in channel_get_participants
    100,
TypeError: __init__() missing 1 required positional argument: 'hash'

**Comment by MaskRay** [comment]
Pushed a new commit. In the latest schema.tl shipped with Telethon, `tl.functions.channels.GetParticipantsRequest` accepts one extra argument `hash:int`.

**Comment by MaskRay** [comment]
Yes, sometimes participants are missing.
