### ISSUE TITLE
Quotes to self posts are misassociated.

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#15]
If anyone quotes a post you made, at least in a supergroup, the 'Re: USERNAME, MESSAGE' part comes up not referencing the post others are quoting.

**Comment by MaskRay** [comment]
Sorry, I do not understand this. Can you elaborate? The `Re` line comes from ~line  2075

```python
                        line = '\x0315「Re {}: {}」\x0f{}'.format(
                            client.nick if user == server else user.nick, refer_text, line)
```

If there are several IRC clients connected, the nick of an arbitrary client will be recorded in the log.

**Comment by rodneyrod** [comment]
When a person is replying to a post I made, the 'Re: ...' part doesn't display my post but just an arbitrary post in the room.

**Comment by MaskRay** [comment]
Can't reproduce.. I fixed a WebPage bug yesterday. Are you using the latest version?

**Comment by MaskRay** [comment]
You are right. `reply` works fine in groups, but not in supergroups.

**Comment by MaskRay** [comment]
Should work now.
