### ISSUE TITLE
Webpages display as gibberish

### ISSUE THREAD

**Issue by vanya-klimenko** [MaskRay/telegramircd#18]
When a received link has Telegram preview, it displays incorrectly and URL is not shown. For example:
```
[webpage] {'webpage': {'id': 1616137859779238602, 'date': datetime.datetime(2018, 1, 12, 13, 12, 35)}}
```

**Comment by vanya-klimenko** [comment]
Okay, I was using a wrong branch. Sorry!

**Comment by rodneyrod** [comment]
I get the same issue intermittently
