### ISSUE TITLE
Image captions or text in messages containing a URL are not shown

### ISSUE THREAD

**Issue by JiK** [MaskRay/telegramircd#19]
I'm using branch `master` (commit `5b84bbf9f08032a8ab6517dfa3e9f47fe9f6b28a`) of telegramircd and version 0.16.2.2 of telethon (obtained by `pip3 install telethon`). (Edit: I updated telethon to 0.16.2.3, but the bug remains.)

---

Whenever someone sends an image with a caption, my IRC client only gets the image url created by telecramid, not the caption. Whenever someone sends a message containing an URL, I only get or the webpage and its title information, not the full message.

---

Examples:

This is what Telegram web client shows for image with caption: https://i.imgur.com/5telBU6.png

But my IRC client only shows: `13:23:33 <xx> [photo] https://[xx]/document/2.jpg`

Telegram web for a message containing a URL: https://i.imgur.com/yQQAV8j.png

IRC: `13:30:18 <xx> [WebPage] https://github.com/MaskRay/telegramircd MaskRay/telegramircd`

**Comment by JiK** [comment]
Ok, apparently all media updates (including webpages) are handled in `Server.on_telegram_update_message()`. The issue can be fixed with a quick hack by adding some lines at the end of the [if block that handles media](https://github.com/MaskRay/telegramircd/blob/5b84bbf9f08032a8ab6517dfa3e9f47fe9f6b28a/telegramircd.py#L2041-L2075).

```
            if msg.message != '':
                text = msg.message + ' ' + text
            if hasattr(msg.media, 'caption'):
                text = msg.media.caption + ' ' + text
```

This duplicates all URLs and looks a bit ugly but it works for now. But I think there should be a more elegant way to ensure all text written by someone else are delivered to the user.

**Comment by MaskRay** [comment]
Thx. Pushed the hack. Dunno if it works
