### ISSUE TITLE
Possible to run headless?

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#2]
I've noticed that you can run Chromium in a headless (no GUI) mode now which would make this application a lot more portable.
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

Would it be possible to somehow integrate this library into your project? That would eliminate the need for a desktop client to have the web.telegram.com webpage open all the time.

**Comment by MaskRay** [comment]
I do not figure out how to compile the project...

You can create a new profile of chrome/chromium, install Greasemonkey, run a headless display server Xvfb.

```
xvfb-run /opt/google/chrome/google-chrome --user-data-dir=$HOME/.config/google-chrome-telegramircd web.telegram.org
```

**Comment by MaskRay** [comment]
Added instructions to README.md

https://github.com/MaskRay/telegramircd/commit/c61ed1c0c6a8aaefa9ec12354b13721f7269429b

**Comment by rodneyrod** [comment]
Thanks this is pretty much all that was needed

**Comment by MaskRay** [comment]
Just a reminder in case you are using this project, I've changed refactored the naming convention of command line options, `--tls-key` and `--tls-cert` have been renamed to `--http-key` `--http-cert`, and `--irc-key --irc-cert` have been added.

**Comment by rodneyrod** [comment]
>Create a new browser user profile with /opt/google/chrome/google-chrome --user-data-dir=$HOME/.config/google-chrome-telegramircd https://web.telegram.org, and do the aforementioned configuration.

When you say 'do the aforementioned configuration', how exactly are you supposed to accomplish this on a headless setup with no GUI to configure in Chrome?

**Comment by MaskRay** [comment]
Install x2goserver on your server, x2goclient to your server
or
ssh -X $server

**Comment by MaskRay** [comment]
I have migrated from webogram (web.telegram.org) to telegram-cli and it should be much easy to use now.
