### ISSUE TITLE
Error when running telegramicd.py

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#4]
When running 'python3 ./telegramircd.py'

File "telegramircd.py", line 57
    async def send_command(self, command, timeout=None):
            ^
SyntaxError: invalid syntax

Installed the dependencies and followed the instructions in the readme and this still occurs, on Ubuntu 14.04.

**Comment by rodneyrod** [comment]
That ^ is supposed to be under the 'f' in 'def' by the way.

**Comment by MaskRay** [comment]
I think the version shipped with Ubuntu 14.04 is python 3.4 . I use the async/await feature which is only available for python >= 3.5 .

**Comment by rodneyrod** [comment]
Yep, you're right on this, thanks for pointing that out.
