### ISSUE TITLE
Groups showing up as users, not channels, when first connecting to telegramircd

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#6]
After updating to the latest build, I'm getting an issue where every time I reset the daemon and connect to it for the first time again, it adds a list of my groups, but it adds them as users instead of channels, and when it starts fetching messages from those groups, it just creates new channels leaving the ones created at the initialisation and it fills up my room list with duplicates.

**Comment by rodneyrod** [comment]
The only message that shows up in those groups is along the lines of:

>* Topic for &[CHAT NAME] is "channel#5555555 [CHAT NAME]"

Or

>Topic for &[CHAT NAME] is "chat#5555555 [CHAT NAME]"

**Comment by MaskRay** [comment]
Strange. Can I run telegramircd with `--password a` and type `eval a client.peer_id2special_room` to diagnose? It is a `dict` from `peer_id` to `SpecialChannel` (representation of a Telegram `chat/group`)

**Comment by rodneyrod** [comment]
Here's that dump, hope it helps.
https://gist.github.com/rodneyrod/232dd547e0e533c6ab84472fefb62a34

**Comment by MaskRay** [comment]
Can you update to HEAD ?  I have changed a lot ...

**Comment by rodneyrod** [comment]
Just checked out the info, if you were wondering if the issue occurs in chats and channels, it is.

**Comment by MaskRay** [comment]
Sorry for you inconvenience... But I have 'git push -f' a lot...

**Comment by rodneyrod** [comment]
Just rm'd and cloned the repo again (git pull throwing ident errors) but still have the same issue.

**Comment by MaskRay** [comment]
If I were you, I would log the output of `telegram-cli --json` and insert a line `print(data)` before line 71 `if isinstance(data, dict) and data.get('result') == 'FAIL':` and line 135 `buf = decoded[j:].encode()` to see the discrepancy... It is very difficult to diagnose without this information.

**Comment by MaskRay** [comment]
`chat/channel/contact`s are initialized in the call site of `channel_list` `contact_list` `dialog_list` (around line 1444). You can type these commands to `telegram-cli --json` to see whether they are different from the `"to"` field in incoming messages.

{"event": "message", "id": "050000007aa8613f5395000000000000653848c956b2b8f8", "flags": 256, "reply_id": "050000007aa8613f4e95000000000000653848c956b2b8f8", "from": {"id": "$010000009f187b0ca76f4af5a7c4db7f", "peer_type": "user", "peer_id": ......, "print_name": "....", "flags": 1, "first_name": "...", "when": "2017-02-09 20:47:06", "last_name": "", "username": "....."}, "to": {"id": "$050000007aa8613f653848c956b2b8f8", "peer_type": "channel", "peer_id": 1063364730, "print_name": "🌊TUNA_Bot_污水群", "flags": 524289, "title": "🌊TUNA Bot 污水群", "participants_count": 0, "admins_count": 0, "kicked_count": 0}, "out": false, "unread": false, "service": false, "date": 1486701137, "text": "可怜的喵呜"}

**Comment by rodneyrod** [comment]
Okay, I haven't gotten around to running those commands again, but after the latest update I can see that the issue is only occurring in supergroups now ('channels' I think they're called), if that helps at all.

**Comment by MaskRay** [comment]
As I mentioned in <https://github.com/MaskRay/telegramircd#known-issues>, channels are not well supported by telegram-cli. There is a mysterious issue that messages do not arrive for some supergroups ( https://github.com/vysheng/tg/issues/1135 ). I work around that by executing the `history` command periodically to pull messages from the server.

**Comment by rodneyrod** [comment]
I've checked the behaviour after the latest update, the issue persists, but I think I might know the issue.
I've noticed that these 'ghost users' with the same names as rooms will only appear once someone starts posting to the actual telegram room, so it happens the same time as the room channel becomes active.

I think that the room ident is somehow being pushed as a direct message over IRC then showing in the actual room as it should be.

**Comment by MaskRay** [comment]
Do you mean an IRC message like `:&archlinux-cn MODE &archlinux-cn +o cuihao` which is displayed as `Mode &archlinux-cn [+o cuihao] by &archlinux-cn`?

**Comment by rodneyrod** [comment]
Yes, similar to that. It's a bit more like:

>Topic for &archlinux-cn is "channel#5555555 &archlinux-cn~!"

**Comment by MaskRay** [comment]
> Topic for &archlinux-cn is "channel#5555555 &archlinux-cn~!"

Where does this message mention the actor?

**Comment by rodneyrod** [comment]
It doesn't, it shows up in my IRC client as a direct message from a user, and the name of the user is just the name of the room without the '&' at the start.

**Comment by MaskRay** [comment]
Can you connect to telegramircd with WeeChat (my favorite IRC client) and press `A-j A-r` (https://weechat.org/files/doc/stable/weechat_user.en.html 
/server raw) and dump the relevant raw IRC message?

**Comment by rodneyrod** [comment]
The issue doesn't appear to be occurring in Weechat, every group shows up normally. I use Quassel normally so that could be why I've noticed the issue.

**Comment by rodneyrod** [comment]
The only line that I can see that would look closest to the one that I get in Quassel is this:

>05:57:11 --> telegram | :telegramircd.maskray.me 332 [SYSTEM USER NAME]&[CHANNEL_NAME]:chat#55555555 [CHANNEL_NAME]

**Comment by MaskRay** [comment]
For WeeChat, a channel name `&channel` can be the source. Quassel may have a different idea on what can be an event source.

**Comment by rodneyrod** [comment]
This is odd, since it was working fine in Quassel before the big refactor you did when I first submitted this issue.

**Comment by MaskRay** [comment]
Can you update to `HEAD` and see whether the issue persists? I have installed Quassel and found chats/channels shown as users. But after deleting `~test/.config/quassel-irc.org`, I can not reproduce the issue.

**Comment by MaskRay** [comment]
Will you see chats/channels shown as users if you do not use the `LIST` command?

**Comment by rodneyrod** [comment]
Issue looks to be resolved now, whatever you did it worked.

**Comment by rodneyrod** [comment]
I just cloned the repo again and the issue appears to have come back. Have you reverted your changes?

**Comment by MaskRay** [comment]
No, I think the issue may be caused by the way Quassel handle 322 332 response codes. Can you comment out one of the two statements I mentioned before?

> I cannot reproduce the issue if I comment out either `client.reply('322 {} {} {} :{}', client.nick, channel.name,` or `client.reply('332 {} {} :{}', client.nick, self.name, self.topic)` .
I think this may be a bug of Quassel.

**Comment by rodneyrod** [comment]
All good, I'll go and apply those changes and report back.

**Comment by rodneyrod** [comment]
I tried to apply those comments, if I just commented out the lines you mentioned and only those lines it does not run, it says there are syntax errors and doesn't run. If I comment out the surrounding arguments it runs but throws up errors and it still has the same issue.

**Comment by MaskRay** [comment]
`JOIN` commands have no effect on the log. You can search for call sites of the `irc_log` function, currently only messages are recorded.

**Comment by rodneyrod** [comment]
All good then, so what are the exact lines that I need to comment out to prevent this issue from occurring, without Python syntax errors?

**Comment by MaskRay** [comment]
These lines
```python
        #for channel in channels:
        #  client.reply('322 {} {} {} :{}', client.nick, channel.name,
        #                channel.n_members(client), channel.topic)
        client.reply('323 {} :End of LIST', client.nick)
```

or

```python
        if self.topic != topic:
            self.topic = topic
        #    for client in server.auth_clients():
        #       client.reply('332 {} {} :{}', client.nick, self.name, self.topic)
```

**Comment by rodneyrod** [comment]
First option fixed it, thank you so much for your patience.

**Comment by MaskRay** [comment]
Quassel does not seem to support channel names with prefixes `&`. I have added an option `--special-channel-prefix '##'` as a workaround.

**Comment by rodneyrod** [comment]
All good, I'll ping the Quassel team about this, hopefully get this all fixed up on that end.
In the meantime, I updated and ran with the new command, but my groups and channels don't load. When Quassel tries to auto join, it errors 'No such channel', and even when people post in the groups and channels I'm part of nothing comes through on IRC.

**Comment by rodneyrod** [comment]
@MaskRay I pinged the Quassel devs over at #quassel at Freenode and they're looking into this issue, but they're having problems with getting the setup working. I've already tried to help them out, but if you could have a quick word over there I think that would be best.

**Comment by MaskRay** [comment]
@rodneyrod I added `005 RPL_ISUPPORT` in HEAD

```python
            self.reply('005 {} PREFIX=(ohv)@%+ CHANTYPES=!#& CHANMODES=,,,m SAFELIST :are supported by this server', self.nick)
```

```
<genius3000> Cool, if that doesn't fix the Quassel client issue for your users, best would be for them to open an issue on the Quassel bug tracker, as detailed as possible.
```
