### ISSUE TITLE
Myself is double posting

### ISSUE THREAD

**Issue by rodneyrod** [MaskRay/telegramircd#7]
In my groups, I see two users, [USERNAME] and [USERNAME]1
Whenever I post in a group, on my IRC client it double posts, with my reply being posted by both [USERNAME] and [USERNAME]1.

The double post does not occur in the actual chat room on Telegram, checked with Telegram Web and only one post was showing.

**Comment by MaskRay** [comment]
What do you mean by `my groups`?

**Comment by rodneyrod** [comment]
Channels and chat groups

**Comment by MaskRay** [comment]
Can you dump relevant IRC messages to me? (Alt-j Alt-r in weechat)

**Comment by rodneyrod** [comment]
│05:49:39 <-- telegram | PING 127.0.0.1
                                           │05:49:39 --> telegram | :telegramircd.maskray.me PONG telegramircd.maskray.me :127.0.0.1
                                           │05:49:40 <-- telegram | PRIVMSG &[CHANNEL_NAME] :test
                                           │05:49:40 --> telegram | :[USERNAME]!555555555@Telegram PRIVMSG &[CHANNEL_NAME] :test

**Comment by rodneyrod** [comment]
I posted the log above, that happens whenever I reply to a chat group or channel. After that it continues to log normal activity.

**Comment by MaskRay** [comment]
I cannot see any issue in the log.....

**Comment by MaskRay** [comment]
Do you mean having two clients connected to telegramircd and sending messages from one client to the other? OK, now I prohibit this kind of `PRIVMSG`.

**Comment by rodneyrod** [comment]
Yep, looks to be fixed now.

**Comment by rodneyrod** [comment]
I just cloned the repo again and the issue appears to have come back. Have you reverted your changes?

**Comment by rodneyrod** [comment]
Found out why this is intermittent on my end. 
First, I setup telegramircd to startup as a service and I wrote my own short upstart script to get it to work.
If I start up telegramircd after a reboot, I have no issue, only one user with my name is displayed e.g. rodneyrod
If I stop the process and start it again though, my name is now duplicated e.g. rodneyrod, rodneyrod1 show up in the user lists.

**Comment by MaskRay** [comment]
Thd older version (one or two weeks ago) of `telegramircd.py` does not remove the `client` instance after an IRC client exits, thus the nick will no longer be available for later IRC clients. It should have been fixed now.

**Comment by rodneyrod** [comment]
I removed the old directory and git clone it again, but the issue is persisting.

**Comment by MaskRay** [comment]
> If I stop the process and start it again though,
Do you mean restarting `telegramircd.py`?

**Comment by rodneyrod** [comment]
Yes, did that and also stop / start the process, same issue.

**Comment by MaskRay** [comment]
I have run `community/quassel-monolithic 0.12.4-3` (Arch Linux) for a while and all seems good. I have no idea the two issues you encountered........ Do these issues persist if you switch to another client (say WeeChat)?

BTW, you can specify `--irc-nicks ray ray1 ray2` to reserve nicks for your IRC clients so they won't occupied by `SpecialUser`

**Comment by rodneyrod** [comment]
Got some more info about the issue. I'll substitute some of the fields that need to be changed.

For the user that displays as rodneyrod:
Hostmask: hostname@127.0.0.1

For the user that displays as rodneyrod1:
Modes: v
Real Name: Rodney Rod
Hostmask: 555555555@telegram
Server: telegramircd.maskray.me

I'll check the client with weechat once I get back home.

**Comment by MaskRay** [comment]
```
% telegram-cli --json
```
Check the `"flags"` fields in "from" or "to" that represent yourself.

The first several lines of `ensure_special_user` checks whether the `flags` of user info indicates `USER_FLAG_SELF` (I am not sure what these bit flags mean, and I may be wrong to use `USE_FLAG_SELF = 0x3`)
```python
    def ensure_special_user(self, record):
        debug('ensure_special_user %r', record)
        if (record.get('flags', 0) & USER_FLAG_SELF) == USER_FLAG_SELF:
            return self     # means the Server instance
```

**Comment by MaskRay** [comment]
It turns out that tgl uses `TGLUF_SELF = 1<<19` to recognize `self`. I have updated `telegramircd.py` to handle this.
https://github.com/MaskRay/telegramircd/blob/master/telegramircd.py#L751
